Repository PHPCSStandards/composer-installer, pull requests merged in 2018-10, with the labels that each got.

#67 Updates copyright year
  LICENSE.md
  README.md
  src/Plugin.php
Labels: documentation

#66 Enforces PSR12
  phpcs.xml.dist
Labels: improvement

#68 Updates contact information
  CONTRIBUTING.md
  composer.json
  src/Plugin.php
Labels: documentation, improvement

#69 Updates README, spelling/grammar, removed Working section
  README.md
Labels: documentation

#51 Move loadInstalledPaths from init to onDependenciesChangedEvent
  src/Plugin.php
Labels: improvement

#46 Adds the ability to set the max depth from the composer.json file
  README.md
  src/Plugin.php
Labels: feature request

#73 Ensures absolute paths during detection phase
  src/Plugin.php
Labels: improvement
