Repository PHPCSStandards/composer-installer, pull requests merged in 2020-01, with the labels that each got.

#94 Improve GH issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#95 Readme: add section about including this plugin from an external PHPCS standard
  README.md
Labels: documentation

#93 Send an exit code when the script terminates
  src/Plugin.php
Labels: improvement

#96 Adding linting jobs in github action
  .github/workflows/linting.yaml
  .yamllint
Labels: builds / deploys / releases, improvement

#100 GH Actions: minor tweaks:
  .github/workflows/linting.yaml
Labels: builds / deploys / releases

#99 Bug report template: further enhancement
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, improvement

#98 Bug fix: `loadInstalledPaths()` very very broken since PHPCS 3.1.0
  src/Plugin.php
Labels: bug - confirmed

#101 ✏️ Update copyright year.
  LICENSE.md
  README.md
  src/Plugin.php
Labels: documentation

#97 Verify the `installed_paths` after save
  src/Plugin.php
Labels: improvement

#102 Readme: minor tweak now 0.6.0 has been released
  README.md
Labels: documentation

#104 Fix for issue #103
  src/Plugin.php
Labels: bug - confirmed

#105 Bugfix: Composer scripts/commands broken in 0.6.0 update
  src/Plugin.php
Labels: bug - unconfirmed
