Repository PHPCSStandards/composer-installer, pull requests merged in 2020-12, with the labels that each got.

#124 Travis: add build against PHP 8.0
  .travis.yml
Labels: builds / deploys / releases

#126 Sort list of installed paths before saving for consistency
  src/Plugin.php
Labels: improvement

#127 Stabilize a condition
  src/Plugin.php
Labels: bug - confirmed
